"""Public quantization-aware training and BitLinear API."""

from .bit_linear import BitLinear
from .quantization import (
    ActivationQuantizationConfig,
    ActivationQuantizedTensor,
    ActivationQuantizer,
    QuantizationConfig,
    TernaryQuantizedTensor,
    TernaryWeightQuantizer,
    WeightQuantizationConfig,
    dequantize_activation,
    dequantize_ternary_weight,
    fake_quantize_activation,
    fake_quantize_ternary_weight,
    quantize_activation_tensor,
    quantize_ternary_weight,
    weight_absmean_scale,
)
from .ste import (
    clamp_ste,
    floor_ste,
    grad_scale,
    round_ste,
    saturating_clamp_ste,
    sign_ste,
    ste_replace,
    ternary_ste,
)

__all__ = [
    "ActivationQuantizationConfig",
    "ActivationQuantizedTensor",
    "ActivationQuantizer",
    "BitLinear",
    "QuantizationConfig",
    "TernaryQuantizedTensor",
    "TernaryWeightQuantizer",
    "WeightQuantizationConfig",
    "clamp_ste",
    "dequantize_activation",
    "dequantize_ternary_weight",
    "fake_quantize_activation",
    "fake_quantize_ternary_weight",
    "floor_ste",
    "grad_scale",
    "quantize_activation_tensor",
    "quantize_ternary_weight",
    "round_ste",
    "saturating_clamp_ste",
    "sign_ste",
    "ste_replace",
    "ternary_ste",
    "weight_absmean_scale",
]
